-- Apply AFTER 202609130001_billing_sync.sql. Preserves existing business data.
-- Upgrade all devices together: old clients deliberately lose anonymous access.
begin;
alter table public.billing_records alter column cursor set generated by default;
create index if not exists idx_billing_records_cursor on public.billing_records(cursor);
create table if not exists public.billing_sync_access (
 singleton boolean primary key default true check(singleton),
 token_hash text not null
);
alter table public.billing_sync_access enable row level security;
revoke all on public.billing_sync_access from public,anon,authenticated;
-- Generate a private pairing token once. Copy the final result into Settings.
create temporary table new_shop_token(token text) on commit drop;
insert into new_shop_token select replace(gen_random_uuid()::text,'-','')||replace(gen_random_uuid()::text,'-','')
 where not exists(select 1 from public.billing_sync_access);
insert into public.billing_sync_access(singleton,token_hash)
 select true,encode(sha256(convert_to(token,'UTF8')),'hex') from new_shop_token;

drop policy if exists "Allow all on devices" on public.billing_devices;
drop policy if exists "Allow all on records" on public.billing_records;
drop policy if exists "Allow all on ops" on public.billing_operations;
revoke all on public.billing_devices,public.billing_records,public.billing_operations from public,anon,authenticated;
-- Revoke the original unprotected entry points, including default PUBLIC execute.
drop function if exists public.register_billing_device(text);
drop function if exists public.push_billing_records(text,jsonb);
drop function if exists public.pull_billing_records(bigint,integer);

create or replace function public.check_billing_token(p_shop_token text) returns void
language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 if p_shop_token is null or length(p_shop_token)<32 or not exists(
  select 1 from public.billing_sync_access where token_hash=encode(sha256(convert_to(p_shop_token,'UTF8')),'hex')
 ) then raise exception 'Invalid private shop token' using errcode='42501'; end if;
end $$;
revoke all on function public.check_billing_token(text) from public,anon,authenticated;

create or replace function public.register_billing_device(p_device_id text,p_shop_token text) returns void
language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 perform public.check_billing_token(p_shop_token);
 if p_device_id is null or length(p_device_id) not between 1 and 128 then raise exception 'Invalid device'; end if;
 insert into public.billing_devices(device_id) values(p_device_id) on conflict do nothing;
end $$;

create or replace function public.push_billing_records(p_device_id text,p_records jsonb,p_shop_token text) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public as $$
declare
 op jsonb; current_record public.billing_records; saved public.billing_records; previous jsonb;
 accepted jsonb:='[]'; conflicts jsonb:='[]'; answer jsonb;
 operation_key text; expected bigint; client_revision bigint;
begin
 perform public.check_billing_token(p_shop_token);
 if p_device_id is null or length(p_device_id) not between 1 and 128 then raise exception 'Invalid device'; end if;
 if p_records is null or jsonb_typeof(p_records)<>'array' or jsonb_array_length(p_records) not between 1 and 1000 then raise exception 'Invalid batch'; end if;
 perform pg_advisory_xact_lock(hashtextextended('shop_sync',0));
 -- Preflight the complete local operation: never accept stock/payment fragments
 -- when its invoice edit conflicts. Retries of committed operations are safe.
 for op in select value from jsonb_array_elements(p_records) loop
  if coalesce(op->>'kind','') not in ('product','customer','settings','invoice','payment','movement','cancellation') then raise exception 'Invalid kind'; end if;
  if coalesce(length(op->>'id'),0) not between 1 and 200 or jsonb_typeof(op->'payload') is distinct from 'object' or op->'payload'->>'id' is distinct from op->>'id' then raise exception 'Invalid record'; end if;
  client_revision:=(op->>'revision')::bigint;expected:=coalesce((op->>'baseRevision')::bigint,0);
  if client_revision is null or client_revision<1 or expected<0 then raise exception 'Invalid revision'; end if;
  operation_key:=p_device_id||':'||(op->>'kind')||':'||(op->>'id')||':'||client_revision;
  select result into previous from public.billing_operations where operation_id=operation_key;
  if found then
   if previous->'payload' is distinct from op->'payload' then raise exception 'Operation ID reused with different content'; end if;
   continue;
  end if;
  select * into current_record from public.billing_records where kind=op->>'kind' and id=op->>'id' for update;
  if found then
   if current_record.payload is distinct from op->'payload' and
      (current_record.revision<>expected or (current_record.payload->>'deleted'='true' and coalesce(op->'payload'->>'deleted','false')<>'true')) then
    conflicts:=conflicts||jsonb_build_array(jsonb_build_object('id',current_record.id,'kind',current_record.kind,'payload',current_record.payload,'revision',current_record.revision,'cursor',current_record.cursor,'conflict',true));
   end if;
  elsif expected<>0 then raise exception 'Missing base record; full resync required';
  end if;
 end loop;
 if jsonb_array_length(conflicts)>0 then return jsonb_build_object('accepted','[]'::jsonb,'conflicts',conflicts); end if;
 insert into public.billing_devices(device_id) values(p_device_id) on conflict do nothing;
 for op in select value from jsonb_array_elements(p_records) loop
  client_revision:=(op->>'revision')::bigint;
  operation_key:=p_device_id||':'||(op->>'kind')||':'||(op->>'id')||':'||client_revision;
  select result into previous from public.billing_operations where operation_id=operation_key;
  if found then accepted:=accepted||jsonb_build_array(previous);continue;end if;
  select * into current_record from public.billing_records where kind=op->>'kind' and id=op->>'id';
  if found then
   if current_record.payload=op->'payload' then saved:=current_record;
   else
    update public.billing_records set payload=op->'payload',revision=revision+1,
     cursor=nextval(pg_get_serial_sequence('public.billing_records','cursor')),updated_at=now()
     where kind=op->>'kind' and id=op->>'id' returning * into saved;
   end if;
  else
   insert into public.billing_records(kind,id,payload,revision) values(op->>'kind',op->>'id',op->'payload',1) returning * into saved;
  end if;
  answer:=jsonb_build_object('id',saved.id,'kind',saved.kind,'payload',saved.payload,'revision',client_revision,'serverRevision',saved.revision,'cursor',saved.cursor);
  insert into public.billing_operations(operation_id,result) values(operation_key,answer);
  accepted:=accepted||jsonb_build_array(answer);
 end loop;
 return jsonb_build_object('accepted',accepted,'conflicts',conflicts);
end $$;

create or replace function public.pull_billing_records(p_after bigint,p_limit integer,p_shop_token text) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public as $$
declare result jsonb;
begin
 perform public.check_billing_token(p_shop_token);
 select coalesce(jsonb_agg(r order by r.cursor),'[]'::jsonb) into result from (
  select id,kind,payload,revision,cursor from public.billing_records where cursor>greatest(coalesce(p_after,0),0) order by cursor limit least(greatest(coalesce(p_limit,250),1),250)
 ) r;
 return result;
end $$;
revoke all on function public.register_billing_device(text,text),public.push_billing_records(text,jsonb,text),public.pull_billing_records(bigint,integer,text) from public;
grant execute on function public.register_billing_device(text,text),public.push_billing_records(text,jsonb,text),public.pull_billing_records(bigint,integer,text) to anon,authenticated;
-- This token is shown only on first application; store it privately.
select token as private_shop_token from new_shop_token;
commit;
