-- DIRECT MULTI-DEVICE SYNC (No login, no passwords, instant direct sync)
-- Execute in your Supabase SQL Editor (Dashboard > SQL Editor > Run)

-- 1. Ensure cursor column is GENERATED BY DEFAULT so updates can advance sync cursors (fixes PostgresException 428C9)
do $$
begin
  if exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' and table_name = 'billing_records' and column_name = 'cursor'
  ) then
    alter table public.billing_records alter column cursor set generated by default;
  end if;
exception when others then
  null;
end $$;

-- 2. Drop old functions to resolve any potential overloading conflicts
drop function if exists public.register_billing_device(text);
drop function if exists public.register_billing_device(text, text);
drop function if exists public.push_billing_records(text, jsonb);
drop function if exists public.push_billing_records(text, jsonb, text);
drop function if exists public.pull_billing_records();
drop function if exists public.pull_billing_records(bigint);
drop function if exists public.pull_billing_records(bigint, integer);
drop function if exists public.pull_billing_records(bigint, integer, text);

-- 3. Create tables if not existing (with GENERATED BY DEFAULT for cursor)
create table if not exists public.billing_devices (
  device_id text not null primary key,
  registered_at timestamptz not null default now()
);

create table if not exists public.billing_records (
  kind text not null,
  id text not null,
  payload jsonb not null,
  revision bigint not null default 1,
  cursor bigint generated by default as identity,
  updated_at timestamptz not null default now(),
  primary key(kind, id)
);

create table if not exists public.billing_operations (
  operation_id text not null primary key,
  result jsonb not null
);

create index if not exists idx_billing_records_cursor on public.billing_records (cursor);

-- Enable row level security and allow read/write for anon and authenticated
alter table public.billing_devices enable row level security;
alter table public.billing_records enable row level security;
alter table public.billing_operations enable row level security;

drop policy if exists "Allow all on devices" on public.billing_devices;
drop policy if exists "Allow all on records" on public.billing_records;
drop policy if exists "Allow all on ops" on public.billing_operations;

create policy "Allow all on devices" on public.billing_devices for all to anon, authenticated using (true) with check (true);
create policy "Allow all on records" on public.billing_records for all to anon, authenticated using (true) with check (true);
create policy "Allow all on ops" on public.billing_operations for all to anon, authenticated using (true) with check (true);

grant all on public.billing_devices, public.billing_records, public.billing_operations to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- 4. Device Registration
create or replace function public.register_billing_device(p_device_id text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if length(p_device_id) not between 1 and 128 then raise exception 'Invalid device'; end if;
  insert into billing_devices(device_id)
  values(p_device_id)
  on conflict do nothing;
end; $$;

-- 5. Push records (supports all kinds including invoice edits, deletions, and payments)
create or replace function public.push_billing_records(p_device_id text, p_records jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  op jsonb;
  current_record billing_records;
  saved billing_records;
  previous jsonb;
  accepted jsonb := '[]';
  conflicts jsonb := '[]';
  answer jsonb;
  operation_key text;
  expected bigint;
  client_revision bigint;
begin
  insert into billing_devices(device_id)
  values(p_device_id)
  on conflict do nothing;

  if jsonb_typeof(p_records) <> 'array' or jsonb_array_length(p_records) > 100 then
    raise exception 'Invalid batch';
  end if;

  -- Concurrency serialization lock
  perform pg_advisory_xact_lock(hashtextextended('shop_sync', 0));

  for op in select value from jsonb_array_elements(p_records) loop
    if coalesce(op->>'kind','') not in ('product','category','customer','settings','shop','invoice','payment','movement','stockMovement','cancellation','draft') then
      raise exception 'Invalid record kind';
    end if;
    if length(coalesce(op->>'id','')) not between 1 and 200 or jsonb_typeof(op->'payload') <> 'object' then
      raise exception 'Invalid record';
    end if;

    client_revision := coalesce((op->>'revision')::bigint, 1);
    expected := coalesce((op->>'baseRevision')::bigint, 0);
    operation_key := p_device_id || ':' || (op->>'kind') || ':' || (op->>'id') || ':' || client_revision::text;

    select result into previous from billing_operations where operation_id = operation_key;
    if found then
      accepted := accepted || jsonb_build_array(previous);
      continue;
    end if;

    select * into current_record from billing_records where kind = op->>'kind' and id = op->>'id' for update;
    if found then
      if current_record.payload = op->'payload' then
        saved := current_record;
      else
        update billing_records
        set payload = op->'payload',
            revision = greatest(revision + 1, client_revision),
            cursor = nextval(pg_get_serial_sequence('public.billing_records','cursor')),
            updated_at = now()
        where kind = op->>'kind' and id = op->>'id'
        returning * into saved;
      end if;
    else
      insert into billing_records(kind, id, payload, revision)
      values(op->>'kind', op->>'id', op->'payload', client_revision)
      returning * into saved;
    end if;

    answer := jsonb_build_object('id', saved.id, 'kind', saved.kind, 'payload', saved.payload, 'revision', client_revision, 'serverRevision', saved.revision, 'cursor', saved.cursor);
    insert into billing_operations(operation_id, result) values(operation_key, answer);
    accepted := accepted || jsonb_build_array(answer);
  end loop;

  return jsonb_build_object('accepted', accepted, 'conflicts', conflicts);
end; $$;

-- 6. Incremental Pull
create or replace function public.pull_billing_records(p_after bigint, p_limit integer)
returns jsonb language sql security definer set search_path = public as $$
  select coalesce(jsonb_agg(r order by r.cursor), '[]'::jsonb) from (
    select id, kind, payload, revision, cursor from billing_records where cursor > p_after order by cursor limit least(greatest(p_limit, 1), 250)
  ) r;
$$;

-- Grant execution to anon and authenticated
grant execute on function public.register_billing_device(text) to anon, authenticated;
grant execute on function public.push_billing_records(text, jsonb) to anon, authenticated;
grant execute on function public.pull_billing_records(bigint, integer) to anon, authenticated;

-- Enable real-time broadcasting on billing_records
do $$
begin
  alter publication supabase_realtime add table public.billing_records;
exception when others then
  null;
end $$;
